#!/bin/sh
#
# Copyright (C) 2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)
boardname="${board##*,}"

case "$board" in
friendlyelec,nanopi-r5s)
	ucidef_set_led_netdev "wan" "WAN" "wan_led" "eth0" "link tx rx"
	ucidef_set_led_netdev "lan1" "LAN1" "lan1_led" "eth1" "link tx rx"
	ucidef_set_led_netdev "lan2" "LAN2" "lan2_led" "eth2" "link tx rx"
	;;
hinlink,opc-h68k-c|\
hinlink,opc-h68k-a)
	ucidef_set_led_netdev "wan" "WAN" "${boardname}:blue:net" "eth0"
	;;
mrkaio,m68s)
	ucidef_set_led_ide "sata" "SATA" "${boardname}:blue:sata"
	;;
esac

board_config_flush

exit 0
